# ex) -Dspring.profiles.active=server|local
mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: mybatis/postgres/*.xml

spring:
    aop:
        auto: true
        proxy-target-class: true
    datasource:
        connectionProperties: characterEncoding=UTF-8
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        type: org.apache.tomcat.jdbc.pool.DataSource
        url: jdbc:log4jdbc:postgresql://postgres.server:65432/postgres
        password: postgres
        username: postgres
        initSQL: select 1
        tomcat:
          validation-query: SELECT 1
          test-on-borrow: true
          validation-interval: 0

    messages:
        basename: i18n/messages
        cache-seconds: -1
        encoding: UTF-8

    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp
    redis:
        host: redis.server
        port: 32771

    test:
        mockmvc:
            print: default


jwt:
    token:
        expiration: 31536000
        header: X-Auth-Token
        origin: local
        secret: __konantech__

permission:
    action: VTT_LOGIN

logging:
    level:
        mybatis:
            mapper: TRACE
        root: WARN
    ROOT: INFO
    com.koknantech.spring: DEBUG


key:
  file: developer.jks




---
spring:
    profiles: developer

